name: Ejecutar Notebook

on:
  workflow_dispatch:  # permite ejecución manual desde la interfaz de GitHub
  schedule:
    - cron: '0 12 * * *'  # se ejecuta todos los días a las 12:00 UTC

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install papermill jupyter

      - name: Ejecutar el notebook
        run: |
          papermill notebooks/mi_script.ipynb notebooks/output.ipynb
