name: Ejecutar Notebook

on:
  workflow_dispatch:
  schedule:
    - cron: '20 1 * * *'  # 21:20 hora Chile

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.17'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install papermill jupyter

      - name: Ejecutar el notebook
        run: |
          papermill mi_script.ipynb output.ipynb
