name: Ejecutar Notebook

on:
  schedule:
    - cron: '45 2 * * *'  # Todos los días a las 22:45 hora local Chile (UTC-4)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: acesped/notebooks
          ref: main

      - name: Listar archivos para debug
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.17'

      - name: Instalar dependencias
        run: pip install notebook nbconvert

      - name: Ejecutar notebook
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: jupyter nbconvert --to notebook --execute mi_script.ipynb --output output.ipynb
